version: "3.8"

services:

    app: 
        image: php:7.2-apache
        ports:
        - 80:80
        environment:  #
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DB:

    mysql:
        image: mysql:5.7
        volumes:
        - mis_datos:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE:

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
        - 8080:8080
        environment:
        - PMA_ARBITRARY=1

networks:
volumenes:

    #extensiones docker visual studio