version: '3'
services:
  apachephp:
    build: .
    container_name: apachephp
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - backend
      - frontend
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpma
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - backend
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes: 
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    networks:
      - backend
networks:
  backend:
  frontend: